### ISSUE TITLE
This is cool, you should host this

### ISSUE THREAD

**Issue by nfischer** [MatteoVH/spectrum-testing#1]
This is a very cool project! You should host this on github pages (it's free). You only need to rename your file to `index.html` and create a gh-pages branch.

If you're an npm user, feel free to check out [the tool I built](https://github.com/nfischer/deploy-gh) to deploy my projects to gh-pages.

**Comment by MatteoVH** [comment]
Thanks Nate! I just threw it up if you want to go play with it. I had no idea it was so easy.

**Comment by nfischer** [comment]
Nice! Looks pretty good. I also personally like to stick the link in the project description, since that makes it a bit easier to reach.

Definitely a neat way to visualize how mathematical functions will perform!
